# Suggested to run with --force-recreate (recreating the container): docker-compose up --force-recreate

services:
  arc_modape_chain:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        - USER_NAME=ubuntu
        - USER_UID=1000
    volumes:
      - .:/arc_modape_chain
      - ./storage:/var/storage    
    command: >
      bash -c "python -m venv --system-site-packages /tmp/.venv 
        source /tmp/.venv/bin/activate
        pip install --upgrade pip
        pip install /arc_modape_chain/modape
        pip install /arc_modape_chain
        pip install -I gunicorn
        mkdir -p /var/storage/FVIIRS2/log
        export PYTHONUNBUFFERED=1
        cd /arc_modape_chain && /tmp/.venv/bin/gunicorn --error-logfile /var/storage/FVIIRS2/log/processing.log --capture-output --workers=1 --threads=1 --bind 0.0.0.0:5001 'wsgi:arc_modape_chain(\"/arc_modape_chain/production.json\")'"
    restart: unless-stopped
    container_name: arc_modape_chain_container
    ports:
      - 5001:5001
