# Use this docker-compose file (or a symlink) in a .devcontainer folder
# which should sit next to the amviewer Git repo checked out in folder "src"

services:

  {{service}}:
    build:
      dockerfile: "{{dockerfile}}"
      context: "{{context}}"
      target: development
    container_name: {{service}}_devcontainer
    ports:
      - "5001:5001"
    user: {{user}}
    restart: unless-stopped
    command: /usr/bin/tail -f /dev/null
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ../:/{{service}}
      - ../storage:/var/storage
