# Use this docker-compose file (or a symlink) in a .devcontainer folder
# which should sit next to the amviewer Git repo checked out in folder "src"
version: '3.8'

services:

  arc_modape_chain:
    build:
      dockerfile: "{{dockerfile}}"
      context: ../docker
      target: development
    container_name: arc_modape_chain_devcontainer
    ports:
      - "8080:5001"
      - "8001:8001"
    restart: unless-stopped
    command: /usr/bin/tail -f /dev/null
    volumes:
      - ../:/arc_modape_chain
#      - /var/data/rvo/AMViewer/bigstorage:/var/bigstorage
#      - /var/data/rvo/AMViewer/leveringen:/var/bigstorage/amviewer
